### ISSUE TITLE
Weiterverwendung von Assets

### ISSUE THREAD

**Issue by skoeltgen** [smeky42/wsjrdp-workadventure#1]
Hast du irgendeine Lizenz zu deinen Assets bzw dürfen wir die für ein Diözesanstufenlager der Pfadfinderstufe verwenden zum Vernetzen von deutschen und irischen Pfadfindern? (Grüne Welle XXL des DV Münster) Wir möchten gerne dafür ein eigenes Workadventure aufsetzen.
Ich soll noch schöne Grüße von Alex ausrichten (einem der Jamboree Finanzer)

**Comment by smeky42** [comment]
Die Assets habe ich von https://opengameart.org/content/lots-of-free-2d-tiles-and-sprites-by-hyptosis und die müssten alle zur freien Verwendung sein. Die Jurte habe ich selbst gemalt und die könnt ihr gerne verwenden. 
Viel Spaß damit! Freut mich wenn ihr was von mir wiederverwenden könnt :-)

Grüße zurück!

**Comment by skoeltgen** [comment]
Besten Dank für die Infos, richte ich aus
